version: 0.0
os: windows
files:
  - source: \simpleWebApplication.1-0.0.1-SNAPSHOT.war
    destination: C:\Users\Administrator\Downloads\apache-tomcat-8.5.57-windows-x64\apache-tomcat-8.5.57\webapps
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
      runas: Administrator
  ApplicationStart:
    - location: \application-start.bat
      timeout: 600
      runas: Administrator
